### PR TITLE
I44 refact rules.py

### LINKED ISSUE #39: Aplicar técnicas de Clean Code no arquivo object_roles.py
Realizar aplicação de técnicas de clean code no arquivo object_roles.py.

**Caminho do arquivo:** /src/ej/roles/object_roles.py 

**Tarefas:**
Aplicar as técnicas:
- [x] Nomes Significativos
- [x] Métodos/Funções
- [ ] Tratamento de Erros
- [x] Comentários
- [x] Formatação/Identação
- [ ] Classes

**Critérios de Aceitação:**
- [ ] Código refatorado baseado no máximo de aplicação possível das técnicas citadas acima.

### PR DESCRIPTION
**Pull request by MatheusFilipe95**
# Descrição
  Foram aplicadas técnicas de clean code em 2 arquivos, object_roles.py e rules.py.

## Issues Relacionadas
  resolves: #39 #44

## Checklist  
- [ ] Os commits seguem o padrão do projeto (Flake8 e afins)
- [ ] Os testes estão passando e cobrem as mudanças 
- [ ] Marcou no título do pull request se ele é work in progress [WIP] ou se está pronto para revisão [REVIEW]

### CODE REVIEW

**Review by thiagoiferreira — APPROVED** [review]

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
I got some problems with the requirement `geocoder`. It seems the same problem I found on #47. I'm starting to suspect that it may be some problem with my machine. I need someone else review.

**Review by filipetoyoshima — APPROVED** [review]
Solved the problem I found. No more issues found :blush:

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
Solve conflicts before merging

**Comment by MatheusFilipe95** [comment]
> Solve conflicts before merging

The conflicts have been solved.

**Review by filipetoyoshima — APPROVED** [review]
It seems to be alright!

**Pull request merged**
